# Generated by Django 4.0.8 on 2022-12-31 00:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='vente',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
