# Generated by Django 4.0.8 on 2022-12-31 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_category_options_alter_vente_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
